version: 2
project_name: kubectl-drill
builds:
- id: kubectl-drill
  main: .
  binary: kubectl-drill
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: windows
    goarch: arm64
  ldflags:
  - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .Date }}

archives:
- builds:
  - kubectl-drill
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  wrap_in_directory: false
  format: tar.gz
  files:
  - LICENSE
